### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by brettdh** [vfarcic/docker-swarm-networking#1]
I would love to use some of this as a starting point for my own swarm setup. Could you add a LICENSE file that specifies the license under which this code is released?

**Comment by vfarcic** [comment]
The license has been added.

By the way, few days I published 70% of my new book. The next chapter that will be added in a week or two will go into more details about clustering and networking with Docker and Docker Swarm. You might want to check it out.

https://leanpub.com/the-devops-2-toolkit
